### ISSUE TITLE
Enable node 16 

### ISSUE THREAD

**Issue by rsharma02-entrata** [aws-actions/configure-aws-credentials#660] opened 2023-02-16 05:50 UTC
### Describe the feature

Can you Enable node 16 as we are getting warnings for this 

### Use Case

Can you Enable node 16 as we are getting warnings for this 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by alexgwolff** [comment] 2023-02-16 20:08
`uses: aws-actions/configure-aws-credentials@v1-node16`

**Comment by bdo** [comment] 2023-02-20 18:44
Duplicate of #489

**Comment by peterwoodworth** [comment] 2023-02-21 02:47
Yes, please see the linked issue #489. A more stable long term solution is in the works. Thanks!

**Closed by peterwoodworth** 2023-02-21 02:47 UTC
Labels: duplicate, feature-request
