### ISSUE TITLE
Assume Role with OIDC with more than 1 hour

### ISSUE THREAD

**Issue by amit-disc** [aws-actions/configure-aws-credentials#354] opened 2022-01-12 12:17 UTC
Hi,

I am using OIDC provider to assume a role with maximum duration set to 8 hours.
I use  role-duration-seconds: 21600 but the credentials expire after 1 hour.

Is it limited to 1 hour?

**Comment by christopher-dG** [comment] 2022-01-13 22:08
After some further investigation, I think I know the root cause: this action sets credentials as environment variables, and doesn't leave any breadcrumbs for SDKs in future steps to refresh them. When assuming a role via OIDC, it should be saving the WebIdentity token and exporting its path as `AWS_WEB_IDENTITY_TOKEN_FILE`. Then, SDKs can fetch credentials and refresh them properly using that file.

**Comment by christopher-dG** [comment] 2022-01-14 13:05
Ha, just realized that the default session duration for OIDC is 1 hour not 6, it's right in the README. So just make sure your role has a long max session duration and then set `role-session-duration` in this action and you can have the session last more than an hour. The credentials still won't refresh though.

**Comment by peterwoodworth** [comment] 2022-10-06 22:51
I'm not able to reproduce this even when using the simple `sleep 61m` repro. I recommend double checking that your role itself has a higher maximum duration than 1 hour, and that you've correctly set the inputs for this action.

Thanks for creating #359 @christopher-dG, it may be the source of the issue. Think we can close this and track that issue instead. If anyone has any reason to believe these are separate issues, ping me and I can look into it

**Closed by peterwoodworth** 2022-10-06 22:51 UTC
Labels: needs-reproduction, p2
