### ISSUE TITLE
self hosted runner behind http / https proxy.

### ISSUE THREAD

**Issue by chenghuang-mdsol** [aws-actions/configure-aws-credentials#421] opened 2022-04-19 22:35 UTC
Environment: self hosted runner behind http / https proxy.
My host is behind a proxy with whitelist policy
I wonder which domains should it be allowed?

**Comment by peterwoodworth** [comment] 2022-10-05 23:19
Closing as duplicate of #222, we should support proxies soon

**Closed by peterwoodworth** 2022-10-05 23:19 UTC
Labels: duplicate
