### ISSUE TITLE
support aws cli installation 

### ISSUE THREAD

**Issue by MushiTheMoshi** [aws-actions/configure-aws-credentials#697] opened 2023-03-17 16:45 UTC
### Describe the feature

Please support aws cli installation as manual installation is not very automation first

### Use Case

I want to have a input with to install or not aws cli

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment] 2023-03-18 00:36
What exactly would be the use case for this? GitHub's runners should automatically have the CLI installed. And on self-hosted runners, I would think most of the time you would want to install the aws cli outside of the action workflow, but maybe you have a legitimate use case for this? If so I would be interested in hearing more about what scenario this would be useful

**Comment by MushiTheMoshi** [comment] 2023-03-18 01:45
On prem runners in enterprise does not install aws cli, also if you are running a job in a container context it will be useful...

**Comment by peterwoodworth** [comment] 2023-03-21 20:21
Thanks @MushiTheMoshi for your input. I'm taking it into consideration

I'm going to be closing this issue as a duplicate of #120, please be sure to give a thumbs up on that issue, as we use that to help us prioritize. There's already quite a few 🙂

**Closed by peterwoodworth** 2023-03-21 20:21 UTC
Labels: feature-request, p2, effort/medium
