### ISSUE TITLE
"Credentials could not be loaded" issue

### ISSUE THREAD

**Issue by chenrui333** [aws-actions/configure-aws-credentials#188] opened 2021-03-18 23:25 UTC
It looks like it happens more often than before. Not quite sure what would be the workaround solution for it.

![image](https://user-images.githubusercontent.com/1580956/111710169-82843c00-881f-11eb-87cd-66b4769da841.png)

**Comment by strongishllama** [comment] 2021-03-19 22:08
I'm getting the same issue, and it always seems whenever I re-run the jobs manually the issue goes away.

**Comment by callum-tait-pbx** [comment] 2021-03-23 15:42
Having the same problem here, any news of an official workaround?

**Comment by paragbhingre** [comment] 2021-03-23 16:45
Thank you for reporting this issue, we have started to take a look into it. We will update you as soon as we find a solution/workaround for this issue.

**Comment by callum-tait-pbx** [comment] 2021-03-23 21:57
😳 this occured for me due to workflows being assigned to incorrect runners due to a misconfiguration on our side, apologies!!! Please ignore my comments.

**Comment by lharress** [comment] 2021-03-24 14:02
We were having this issue as well, it may be related to the Github secrets and read-only token changes. There is more details in this [article](https://securitylab.github.com/research/github-actions-preventing-pwn-requests).

Basically Github secrets are no longer visible to pull requests coming from forks, in addition the `GITHUB_TOKEN` is read only. There are settings to turn those permissions back on but it depends on individual circumstances for the risks. In our case Dependabot is considered a "fork" and you can now provide secrets just for Dependabot.

**Comment by piradeepk** [comment] 2021-03-24 16:00
@chenrui333 thanks for reaching out, I had a couple questions that would help us to debug your issue. 

Are you able to get it to succeed at any point, or is it consistantly failing all the time? Also, based on the previous comment, are you using a fork which has Github Secrets defined in the parent repo, or does your repo itself have the secrets defined? Which Secrets do you have defined (I'm just looking for the Secret Keys, not the actual secret values)?

**Comment by strongishllama** [comment] 2021-03-24 21:21
@piradeepk It sounds like my issue (and likely @chenrui333's too) has to do with the changes @lharress mentioned. If anyone else having the same issue and is wondering how to add secrets to Dependabot, check out [this](https://github.blog/2021-03-15-dependabot-private-dependencies) GitHub blog post.

**Comment by paragbhingre** [comment] 2021-04-01 17:53
@chenrui333 are you still facing this issue? Is it intermittent or continuously occurring?

**Comment by johnpeb** [comment] 2021-04-01 17:58
@paragbhingre this is happening for me for 100% (or almost 100%) of the builds triggered by `dependabot` PRs but never happens for builds I trigger through a push/UI. Also if I re-run failed dependabot PR build this doesn't happen either.

**Comment by piradeepk** [comment] 2021-04-01 18:01
@johnpeb it sounds like [this comment/article](https://github.com/aws-actions/configure-aws-credentials/issues/188#issuecomment-806194355) may be the issue that's impacting you. If you could try suggestions in this article, and let us know if you're still having issues.

**Comment by johnpeb** [comment] 2021-04-01 18:19
Thanks. I spent too long searching how to configure this - here's where it is:
![image](https://user-images.githubusercontent.com/9312/113336866-fb41c880-92f4-11eb-9d21-1b79452c5dc8.png)

**Comment by paragbhingre** [comment] 2021-04-13 16:20
Looks like this issue is occurring because of changes mentioned in [this article](https://github.blog/2021-03-15-dependabot-private-dependencies/). Closing this issue for now. Feel free to reopen if required.

**Closed by paragbhingre** 2021-04-13 16:20 UTC
Labels: investigating

**Comment by chenrui333** [comment] 2021-04-14 00:19
I am gonna check the above suggestions, yes, this is only happened for me with dependabot PRs.

**Comment by marcus-vw** [comment] 2021-05-03 08:57
I had the same Problem, see #202

My problem was caused by a Dependabot changed. 
All Dependabot Pull Requests are now handled like they were from forks which means you can't access any secrets. This will apply to all actions inside a workflow.

https://github.com/dependabot/dependabot-core/issues/3253 helped my to solve my problem. Hopefully it will spare some time for somebody having the same issue.

**Comment by martinschaef** [comment] 2021-12-04 20:08
I get this error message when I do a pull request from a fork:
https://github.com/awslabs/smithy/runs/4418821072?check_suite_focus=true
The role has a trust relationship with `awslabs/*` (e.g., [here](https://github.com/awslabs/aws-crypto-policy-compliance-checker/runs/4413512009?check_suite_focus=true#step:6:3) is an example where it works) and with `martinschaef/*`([here](https://github.com/martinschaef/smithy/runs/4418820965?check_suite_focus=true#step:7:3) is an example where it works), but on the Pull Request between the repos is seems to always fail:
[example 1](https://github.com/awslabs/smithy/actions/runs/1539612871), [example 2](https://github.com/awslabs/smithy/actions/runs/1539601409).

**Comment by richardhboyd** [comment] 2021-12-08 22:08
Was the role set up to use OIDC? Can you share that configuration?

**Comment by martinschaef** [comment] 2021-12-08 22:13
The role was set up using this stack: https://github.com/aws-samples/aws-codeguru-reviewer-cicd-cdk-sample
and the trust relationship looks as follows:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::048169001733:oidc-provider/token.actions.githubusercontent.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringLike": {
          "token.actions.githubusercontent.com:sub": [
            "repo:aws/*:*",
            "repo:awslabs/*:*",
            "repo:aws-samples/*:*",
            "repo:martinschaef/*:*"
          ]
        }
      }
    }
  ]
}
```
